# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-07 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biogrid',
            fields=[
                ('interid', models.IntegerField(db_column='INTERID', primary_key=True, serialize=False)),
                ('entreza', models.IntegerField(db_column='ENTREZA')),
                ('entrezb', models.IntegerField(db_column='ENTREZB')),
                ('officiala', models.CharField(blank=True, db_column='OFFICIALA', max_length=50, null=True)),
                ('officialb', models.CharField(blank=True, db_column='OFFICIALB', max_length=50, null=True)),
                ('system', models.CharField(blank=True, db_column='SYSTEM', max_length=50, null=True)),
                ('systemtype', models.CharField(blank=True, db_column='SYSTEMTYPE', max_length=20, null=True)),
                ('pmid', models.IntegerField(blank=True, db_column='PMID', null=True)),
                ('organisma', models.IntegerField(blank=True, db_column='ORGANISMA', null=True)),
                ('organismb', models.IntegerField(blank=True, db_column='ORGANISMB', null=True)),
                ('throughput', models.CharField(blank=True, db_column='THROUGHPUT', max_length=10, null=True)),
                ('srcdb', models.CharField(blank=True, db_column='SRCDB', max_length=20, null=True)),
            ],
            options={
                'db_table': 'biogrid',
                'managed': False,
            },
        ),
    ]
