# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-09 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_bioplex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emiliome',
            fields=[
                ('emiliid', models.CharField(db_column='EMILIID', max_length=40, primary_key=True, serialize=False)),
                ('entreza', models.IntegerField(blank=True, db_column='ENTREZA', null=True)),
                ('entrezb', models.IntegerField(blank=True, db_column='ENTREZB', null=True)),
                ('symbola', models.CharField(blank=True, db_column='SYMBOLA', max_length=40, null=True)),
                ('symbolb', models.CharField(blank=True, db_column='SYMBOLB', max_length=40, null=True)),
            ],
            options={
                'db_table': 'emiliome',
                'managed': False,
            },
        ),
    ]
