# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-16 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_emiliome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('interid', models.IntegerField(db_column='INTERID', primary_key=True, serialize=False)),
                ('entreza', models.IntegerField(db_column='ENTREZA')),
                ('entrezb', models.IntegerField(db_column='ENTREZB')),
                ('symbola', models.CharField(blank=True, db_column='SYMBOLA', max_length=50, null=True)),
                ('symbolb', models.CharField(blank=True, db_column='SYMBOLB', max_length=50, null=True)),
                ('organisma', models.IntegerField(blank=True, db_column='ORGANISMA', null=True)),
                ('organismb', models.IntegerField(blank=True, db_column='ORGANISMB', null=True)),
                ('system', models.CharField(blank=True, db_column='SYSTEM', max_length=50, null=True)),
                ('systemtype', models.CharField(blank=True, db_column='SYSTEMTYPE', max_length=20, null=True)),
                ('throughput', models.CharField(blank=True, db_column='THROUGHPUT', max_length=10, null=True)),
                ('score', models.FloatField(blank=True, db_column='SCORE', null=True)),
                ('pmid', models.IntegerField(blank=True, db_column='PMID', null=True)),
                ('srcdb', models.CharField(blank=True, db_column='SRCDB', max_length=20, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'interaction',
            },
        ),
    ]
