# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-29 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_interaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ncbiprot',
            fields=[
                ('acc', models.CharField(db_column='ACC', max_length=20)),
                ('cds', models.CharField(blank=True, db_column='CDS', max_length=200, null=True)),
                ('protname', models.CharField(blank=True, db_column='PROTNAME', max_length=1000, null=True)),
                ('eid', models.IntegerField(db_column='EID')),
                ('gi', models.IntegerField(db_column='GI', primary_key=True, serialize=False)),
                ('len', models.IntegerField(blank=True, db_column='LEN', null=True)),
                ('seq', models.CharField(blank=True, db_column='SEQ', max_length=60000, null=True)),
                ('symbol', models.CharField(db_column='SYMBOL', max_length=50)),
                ('taxid', models.IntegerField(blank=True, db_column='TAXID', null=True)),
            ],
            options={
                'db_table': 'ncbiprot',
                'managed': False,
            },
        ),
    ]
