# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-19 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_syns_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refseq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxid', models.IntegerField(db_column='TAXID')),
                ('eid', models.IntegerField(db_column='EID')),
                ('status', models.CharField(blank=True, db_column='STATUS', max_length=20, null=True)),
                ('rna_acc', models.CharField(blank=True, db_column='RNA_ACC', max_length=20, null=True)),
                ('rna_gi', models.IntegerField(blank=True, db_column='RNA_GI', null=True)),
                ('prot_acc', models.CharField(blank=True, db_column='PROT_ACC', max_length=20, null=True)),
                ('prot_gi', models.IntegerField(blank=True, db_column='PROT_GI', null=True)),
                ('gennuc_acc', models.CharField(db_column='GENNUC_ACC', max_length=20)),
                ('gennuc_gi', models.IntegerField(db_column='GENNUC_GI')),
                ('scoord', models.IntegerField(blank=True, db_column='SCOORD', null=True)),
                ('eccord', models.IntegerField(blank=True, db_column='ECCORD', null=True)),
                ('strand', models.CharField(blank=True, db_column='STRAND', max_length=1, null=True)),
                ('assembly', models.CharField(blank=True, db_column='ASSEMBLY', max_length=50, null=True)),
                ('pept_acc', models.CharField(blank=True, db_column='PEPT_ACC', max_length=20, null=True)),
                ('pept_gi', models.IntegerField(blank=True, db_column='PEPT_GI', null=True)),
                ('symbol', models.CharField(blank=True, db_column='SYMBOL', max_length=20, null=True)),
            ],
            options={
                'db_table': 'refseq',
                'managed': False,
            },
        ),
    ]
