# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-06 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_refseq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cdd',
            fields=[
                ('pssm', models.IntegerField(db_column='PSSM', primary_key=True, serialize=False)),
                ('acc', models.CharField(db_column='ACC', max_length=20)),
                ('name', models.CharField(blank=True, db_column='NAME', max_length=20, null=True)),
                ('description', models.CharField(blank=True, db_column='DESCRIPTION', max_length=2000, null=True)),
                ('root', models.IntegerField(blank=True, db_column='ROOT', null=True)),
                ('sub', models.CharField(blank=True, db_column='SUB', max_length=5000, null=True)),
                ('super', models.IntegerField(blank=True, db_column='SUPER', null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'cdd',
            },
        ),
    ]
