# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-13 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_homologene'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enshom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eida', models.IntegerField(db_column='EIDA')),
                ('symbola', models.CharField(blank=True, db_column='SYMBOLA', max_length=30, null=True)),
                ('taxida', models.IntegerField(db_column='TAXIDA')),
                ('eidb', models.IntegerField(db_column='EIDB')),
                ('symbolb', models.CharField(blank=True, db_column='SYMBOLB', max_length=30, null=True)),
                ('taxidb', models.IntegerField(db_column='TAXIDB')),
                ('maptype', models.CharField(blank=True, db_column='MAPTYPE', max_length=30, null=True)),
                ('certainty', models.IntegerField(blank=True, db_column='CERTAINTY', null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'enshom',
            },
        ),
    ]
